date/date/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include('profiles.urls', namespace='profiles')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

date/profiles/urls.py
from django.urls import path
from .views import (
    my_profile_view,
    ProfileView,
    match_received_view,
    accept_match,
    reject_match,
    ProfileListView,
    send_match,
    remove_match,
)

app_name = 'profiles'

urlpatterns = [
    path('myprofile/', my_profile_view, name='my-profile-view'),
    path('<int:pk>', ProfileView.as_view(), name='profile-client'),
    path('my_match/', match_received_view, name='my-match-view'),
    path('my_match/accept/', accept_match, name='accept-match'),
    path('my_match/reject/', reject_match, name='reject-match'),
    path('all_profiles/', ProfileListView.as_view(), name='all-profiles-view'),
    path('send_match/', send_match, name='send-match'),
    path('remove_match/', remove_match, name='remove-match'),
]

date/profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.conf import settings
from django.db.models import Q
from django.core.mail import send_mail


class ProfileManager(models.Manager):

    def get_all_profiles_to_match(self, sender):
        profiles = Profile.objects.all().exclude(user=sender) # все профили кроме отправителя
        profile = Profile.objects.get(user=sender) # отправитель
        qs = Relationship.objects.filter(Q(sender=profile) | Q(receiver=profile)) # фильтр отправитель or получатель

        accepted = ([])
        for rel in qs:
            if rel.status == 'accepted': # заносим в список accepted профили подтвержденных друзей
                accepted.add(rel.receiver)
                accepted.add(rel.sender)

        available = [profile for profile in profiles if profile not in accepted]
        # если профиля нет в общем списке профилей, то добавляем его в список available
        return available

    def get_all_profiles(self, me):
        profiles = Profile.objects.all().exclude(user=me) # все профили кроме себя
        return profiles


class Profile(models.Model):
    GENDER_CHOICES = (
        ('М', 'муж'),
        ('Ж', 'жен'),
    )

    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(default='avatar.png', upload_to='avatars/')
    email = models.EmailField(max_length=200, blank=True)
    match = models.ManyToManyField(User, blank=True, related_name='match')

    objects = ProfileManager()

    def save(self, *args, **kwargs):
        super().save()
        if not self.avatar:
            return
        img = Image.open(self.avatar.path)
        width, height = img.size
        watermark = Image.open(settings.MEDIA_ROOT + '/watermark.png')
        watermark.thumbnail((200, 200))
        mark_width, mark_height = watermark.size
        paste_mask = watermark.split()[0]
        x = width - mark_width - 5
        y = height - mark_height - 5
        img.paste(watermark, (x, y), paste_mask)
        img.save(self.avatar.path)

    def __str__(self):
        return f'{self.user} {self.email}'


class RelationshipManager(models.Manager):
    def invitations_received(self, receiver):
        qs = Relationship.objects.filter(receiver=receiver, status='send')
        return qs


class Relationship(models.Model):
    STATUS_CHOICES = (
        ('send', 'Симпатия'),
        ('accepted', 'Взаимная симпатия')
    )

    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models.CharField(max_length=8, choices=STATUS_CHOICES)

    objects = RelationshipManager()

    def send_match(receiver, sender):
        subject = 'У вас есть пара!'
        message = f'Вы понравились {sender.first_name}!  Почта участника: {sender.email}'
        admin_email = settings.EMAIL
        user_email = [receiver.email]
        return send_mail(subject, message, admin_email, user_email)

    def __str__(self):
        return f'{self.sender}-{self.receiver}-{self.status}'

date/profiles/forms.py
from django import forms
from .models import Profile


class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'gender', 'avatar')

date/profiles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile, Relationship
from .forms import ProfileModelForm
from django.views.generic import DetailView, ListView
from django.contrib.auth.models import User
from django.db.models import Q
from .filters import ProfileFilter


def my_profile_view(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=profile)
    confirm = False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'profile': profile,
        'form': form,
        'confirm': confirm,
    }

    return render(request, 'profiles/myprofile.html', context)


class ProfileView(DetailView):
    model = Profile
    template_name = 'profile_client.html'
    context_object_name = 'profile_client'
    queryset = Profile.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


def match_received_view(request): # вьюха списка полученных запрос в друзья
    profile = Profile.objects.get(user=request.user)
    qs = Relationship.objects.invitations_received(profile)
    result = list(map(lambda x: x.sender, qs)) # lambda функция для создания списка профилей, сделавших запрос на добвление в друзья
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {
        'qs': result,
        'is_empty': is_empty,
    }  # список из профилей сделавших запрос на добавление в друзья (без указания получателя (себя)), если никого - is_empty

    return render(request, 'profiles/my_match.html', context)


def accept_match(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        if rel.status == 'send':
            rel.status = 'accepted'
            rel.save()
    return redirect('profiles:my-match-view')


def reject_match(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        rel = get_object_or_404(Relationship, sender=sender, receiver=receiver)
        rel.delete()
    return redirect('profiles:my-match-view')


class ProfileListView(ListView):
    model = Profile
    template_name = 'profiles/profile_list.html'
    context_object_name = 'qs'
    queryset = Profile.objects.all()

    def get_queryset(self):
        qs = Profile.objects.get_all_profiles(self.request.user)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username__iexact=self.request.user) # iexact возвращает юзернейм без учета регистра знаков
        profile = Profile.objects.get(user=user) # получаем профиль юзера
        rel_r = Relationship.objects.filter(sender=profile) # список отправленных запросов на добавление в друзья
        rel_s = Relationship.objects.filter(receiver=profile) # список принятых запросов на добавление в друзья
        rel_receiver = []
        rel_sender = [] # пустые списки для добавления в них отправленных и принятых запросов в друзья

        for item in rel_r:
            rel_receiver.append(item.receiver.user)

        for item in rel_s:
            rel_sender.append(item.sender.user)

        context['rel_receiver'] = rel_receiver
        context['rel_sender'] = rel_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True
        context['filter'] = ProfileFilter(self.request.GET, queryset=self.get_queryset())

        return context


def send_match(request): # метод отправляет запрос на добавление в друзья другим пользователям
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:all-profiles-view')


def remove_match(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        rel = Relationship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
        )
        rel.delete()
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('profiles:all-profiles-view')

date/profiles/templates/profiles/my_match.html
{% extends 'base.html' %}

{% block title %}
Принятые симпатии
{% endblock title %}

{% block content %}

{% if is_empty  %}
    <h1>Нет симпатий...</h1>
{% endif %}

{% for obj in qs %}
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="three wide column">
                    <img class="ui small circular image" src="{{obj.avatar.url}}">
                </div>
                <div class="thirteen wide column">
                    <h3>{{obj.user}}</h3>
                    <br>
                    <a href="{% url 'profiles:profile-client' obj.pk %}"><button class="ui primary button w-big mb-5">Смотреть профиль</button></a>
                    <form action="{% url 'profiles:accept-match' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{obj.pk}}>
                        <button type="submit" class="ui positive basic button w-big mb-5">
                            <i class="check icon"></i>Принять</button>
                    </form>
                    <form action="{% url 'profiles:reject-match' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value={{obj.pk}}>
                        <button type="submit" class="ui negative basic button w-big mb-5">
                            <i class="close icon"></i>Отклонить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock content %}

date/profiles/templates/profiles/myprofile.html
{% extends 'base.html' %}

{% block title %}
Мой профиль
{% endblock title %}

{% block content %}

<div class="ui modal mymodal">
  <i class="close icon"></i>
  <div class="header">
    Обновить профиль
  </div>
  <div class="image content">
    <div class="ui medium image">
      <img src="{{profile.avatar.url}}">
    </div>
    <div class="description">
      <div class="ui header">Добавить/изменить информацию о себе</div>
      <form action="" method="POST" class="ui form" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
      </div>
  </div>
  <div class="actions">
    <button type="submit" class="ui positive right labeled icon button">
      Обновить
      <i class="checkmark icon"></i>
    </button>
    </form>
  </div>
</div>

<div class="ui segment">
  {% if confirm %}
    <div class="ui green message">Профиль обновлен</div>
  {% endif %}
  <h3>Профиль юзера {{request.user}}</h3>
  <div class="ui grid">
  <div class="row">
      <div class="six wide column">
        <img class="oi medium rounded image" src="{{profile.avatar.url}}">
        <div class="row mt-5">
          <button class="ui secondary button" id="modal-btn">Обновить ваш профиль</button> <!--настройка в static_project/main.js...-->
        </div>
      </div>
    <div class="ten wide column">
      <table class="iu table">
        <tbody>
        <tr>
          <td>Пользователь</td>
          <td>{{profile.user}}</td>
        </tr>
        <tr>
          <td>Имя</td>
          <td>{{profile.first_name}}</td>
        </tr>
        <tr>
          <td>Фамилия</td>
          <td>{{profile.last_name}}</td>
        </tr>
        <tr>
          <td>Пол</td>
          <td>{{profile.gender}}</td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
  </div>
</div>

{% endblock content %}

date/profiles/templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}
Все профили
{% endblock title %}

{% block content %}
{% if is_empty %}
    <h1>Нет подходящих профилей</h1>
{% endif %}

<form method="GET">
    {{ filter.form }}
    <input type="submit" value="Найти">
</form>

{% for obj in filter.qs %}
    <div class="ui segment">
        <div class="ui grid>">
            <div class="row">
                <div class="three wide column">
                    <img class="ui small circular image" src={{obj.avatar.url}}>
                </div>
                <div class="thirteen wide column">
                    <h3>{{obj.user}}</h3>
                    <a href="{% url 'profiles:profile-client' obj.pk %}"><button class="ui primary button mb-5 w-big">Посмотреть профиль</button></a>
                    <br>

                    {% if obj.user not in rel_receiver and obj.user not in rel_sender %}
                        <form action="{% url 'profiles:send-match' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui positive basic button mb-5 w-big"><i class="plus square icon"></i>Симпатия</button>
                        </form>
                    {% endif %}

                    {% if obj.user in rel_receiver and request.user not in obj.match.all %}
                        <button class="ui disabled button mb-5 w-big"><i class="user icon"></i>Ожидание...</button>
                    {% endif %}

                    {% if request.user in obj.match.all %}
                        <form action="{% url 'profiles:remove-match' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{obj.pk}}">
                            <button type="submit" class="ui negative basic button mb-5 w-big"><i class="minus square icon"></i>Отклонить</button>
                        </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endfor %}

{% endblock content %}